udo: required
language: bash

# exclude tags
branches:
  except:
    - /^\d+$/

services:
  - docker

env:
  global:
    - CI_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER

before_install:
  - docker login --username $DOCKER_LOGIN --password $DOCKER_PASS

script:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then make publish && make deploy-prod; else make package; fi

after_success:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$(make version)
  - echo "GIT_TAG=$GIT_TAG"
  - >
    [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] &&
    git tag $GIT_TAG -f -a -m "Version $GIT_TAG built by Travis CI - https://travis-ci.com/$TRAVIS_REPO_SLUG/builds/$TRAVIS_JOB_ID"
    || true
  - >
    [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] &&
    git push -q https://$GITHUB_USER:$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG --tags || true

notifications:
    # dont notify successful builds
    on_success: never

    # always notify build failures
    on_failure: always

